-- DROPS ALL THE TABLES
DROP TABLE Match CASCADE;
DROP TABLE TeamStandingStat CASCADE;
DROP TABLE TeamStanding CASCADE;
DROP TABLE PlayerAward CASCADE;
DROP TABLE PlayerTeam CASCADE;
DROP TABLE PlayerStat CASCADE;
DROP TABLE Award CASCADE;
DROP TABLE LeagueHistory CASCADE;
DROP TABLE Player CASCADE;
DROP TABLE Team CASCADE;
DROP TABLE League CASCADE;