INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Arsenal FC', '1001', '1886', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Aston Villa FC', '1002', '1872', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Chelsea FC', '1003', '1905', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Everton FC', '1004', '1878', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Fulham FC', '1005', '1879', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Liverpool FC', '1006', '1892', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Manchester City FC', '1007', '1880', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Manchester United FC', '1008', '1878', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Newcastle United FC', '1009', '1881', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Tottenham Hotspur FC', '1010', '1882', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('West Bromwich Albion FC', '1011', '1879', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Wolverhampton Wanderers FC', '1012', '1877', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Burnley FC', '1013', '1881', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Leicester City FC', '1014', '1884', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Southampton FC', '1015', '1885', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Leeds United FC', '1016', '1904', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Crystal Palace FC', '1017', '1905', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Sheffield United FC', '1018', NULL, 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Brighton & Hove Albion FC', '1019', '1898', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('West Ham United FC', '1020', '1895', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Norwich City FC', '1021', '1902', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Watford FC', '1022', '1881', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Brentford FC', '1023', '1889', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Nottingham Forest FC', '1024', '1865', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('AFC Bournemouth', '1025', '1890', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Blackburn Rovers FC', '1026', '1874', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Queens Park Rangers FC', '1027', '1882', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Stoke City FC', '1028', '1863', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Swansea City AFC', '1029', '1912', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Birmingham City FC', '1030', '1875', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Derby County FC', '1031', '1884', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Middlesbrough FC', '1032', '1876', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Sheffield Wednesday FC', '1033', '1820', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Reading FC', '1034', '1871', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Barnsley FC', '1035', '1887', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Millwall FC', '1036', '1885', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Rotherham United FC', '1037', '1870', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Bristol City FC', '1038', '1894', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Luton Town FC', '1039', '1885', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Huddersfield Town AFC', '1040', '1908', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Cardiff City FC', '1041', '1899', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Coventry City FC', '1042', '1883', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Preston North End FC', '1043', '1863', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Wycombe Wanderers FC', '1044', '1887', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Hull City AFC', '1045', '1904', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Blackpool FC', '1046', '1887', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Peterborough United FC', '1047', '1934', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Sunderland AFC', '1048', '1879', 'United Kingdom');
INSERT INTO Team(team_name, team_id, year_founded, country) VALUES ('Wigan Athletic FC', '1049', '1932', 'United Kingdom');
